
FROM quay.io/openshift/origin-jenkins-agent-base
USER root
RUN curl -o get-pip.py https://bootstrap.pypa.io/get-pip.py \
&& python get-pip.py \
&& curl -o requirements.txt https://raw.githubusercontent.com/MoOyeg/testFlask/master/requirements.txt \
&& pip install -r requirements.txt
USER 1001
