kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: finalizer-role-jenkins
rules:
  - verbs:
      - '*'
    apiGroups:
      - '*'
    resources:
      - deployments/finalizers
      - pods/finalizers
      - deploymentconfigs/finalizers



